# Generated by Django 6.0.3 on 2026-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_department_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10),
        ),
    ]
