# Generated by Django 5.2.5 on 2026-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_id_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('SUBMITTED_ON_SPECIAL_EXTENSION', 'Submitted on Special Extension'), ('SUBMITTED_ON_EXTENSION', 'Submitted on Extension'), ('GRADED', 'Graded')], default='PENDING', max_length=40),
        ),
    ]
