# Generated by Django 5.2.8 on 2026-04-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_submission_status'),
        ('student', '0007_alter_student_id'),
        ('teacher', '0007_alter_department_id_alter_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_due_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='assignments.assignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_extensions', to='teacher.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_extensions', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
