# Generated by Django 6.0.3 on 2026-04-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ENROLLED', 'Enrolled'), ('GRADUATED', 'Graduated'), ('DROPPED_OUT', 'Dropped Out')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
