# Generated by Django 6.0.3 on 2026-04-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_registration_number'),
        ('student', '0003_student_status_alter_student_registration_number'),
    ]

    operations = [
    ]
