# Generated by Django 6.0.3 on 2026-04-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_merge_20260403_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
