name: Quality Assurance

on:
    workflow_call:  # Makes this reusable from other workflows
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'

jobs:
    quality-assurance:
        name: Quality Assurance
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Create a virtual environment
              run: python -m venv .venv

            - name: Install dependencies
              run: |
                venv/bin/pip install -r requirements.txt
                venv/bin/pip install ruff

            - name: Run lint
              run: |
                venv/bin/ruff check .
